#!/bin/bash
DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
cp -pf $DIR/developer /usr/bin/dev
echo "INFO: developer hook updated."
if [ "$DIR" == "/usr/bin" ]; then
    DIR=/iisi-developer
    . $DIR/developer $*
else
    . $DIR/bin/setenv $*
    if [ "$DEV_HOME" != '' ]; then
        cd $DEV_HOME
    fi
fi
