#!/bin/bash
if [[ "$SHELL" =~ bin/zsh ]]; then
    echo "Can't support!!!"
fi
if [[ "$(uname)" = "Darwin" ]]; then
    # Mac OS X
    DIR=$(pwd)
elif [[ "$(expr substr $(uname -s) 1 5)" = "Linux" ]] ; then
    # GNU/Linux
    echo Linux
elif [[ "$(expr substr $(uname -s) 1 5)" = "MINGW" ]] ; then
    # Windows NT
    DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
    if [ -e $DIR/developer ]; then
        cp -pf $DIR/developer /usr/bin/dev
        echo "INFO: developer hook updated."
    fi
fi
if [ ! -n $DIR ]; then
    echo "Can't support!!!"
fi
if [[ "$DIR" == "/usr/bin" ]]; then
    DIR=/iisi-developer
    . $DIR/developer $*
else
    . $DIR/bin/setenv $*
    if [ "$DEV_HOME" != '' ]; then
        cd $DEV_HOME
    fi
fi

