#!/bin/bash
##
## Download application archive via curl command
##
archiveType="zip"

while [ $# -gt 0 ]; do
    if [[ $1 == "--type" ]]; then
        shift
        archiveType=$1
    elif [[ $1 == "--url" ]]; then
        shift
        downloadUrl=$1
    elif [[ $1 == "--name" ]]; then
        shift
        appName=$1
    elif [[ $1 == "--file" ]]; then
        shift
        localFile=$1
    fi
    shift
done

if [[ $downloadUrl == "" ]]; then
    echo "Usage: downloadapp --type <archive-type> --url <download-url> --name <application-name> [--file <local-file>]"
    exit 1
fi

if [[ $localFile != "" ]]; then
    ## Get the file name from the local file path
    appName=$(basename $localFile)
fi

downloadArchivePath="$DEV_HOME/tmp"

if [[ $archiveType == "zip" ]]; then
    if [[ -f $downloadArchivePath/$appName.zip ]]; then
        rm -rf $downloadArchivePath/$appName.zip
    fi
    if [[ $localFile != "" ]]; then
        cp $localFile $downloadArchivePath/$appName.zip
    else
        curl -L -o $downloadArchivePath/$appName.zip $downloadUrl
    fi
elif [[ $archiveType == "exe" ]]; then
    curl -L -o $downloadArchivePath/$appName.exe $downloadUrl
fi

## Return the path of the downloaded archive
echo "$downloadArchivePath/$appName.$archiveType"
