#!/bin/bash

while [ $# -gt 0 ]; do
    if [[ $1 == "--name" ]]; then
        shift
        appBinary=$1
    elif [[ $1 == "--command" ]]; then
        shift
        appCommand=$1
    fi
    shift
done

appBinaryPath=$DEV_HOME/usr/bin/$appBinary

echo "#!/bin/bash" > $appBinaryPath
echo -e "$appCommand" >> $appBinaryPath

chmod +x $appBinaryPath
