#!/bin/bash
#### 7-Zip
if [[ "$DEV_ENV_OS" =~ ^msys.*$ ]]; then
    export ZIP7_HOME=$DEV_HOME/opt/7zip
    if [[ ! "$PATH" =~ $ZIP7_HOME ]]; then
        export PATH=$PATH:$ZIP7_HOME
    fi
elif [[ "$DEV_ENV_OS" =~ ^darwin.*$ ]]; then
    if [[ "$(which 7za)" == '' ]]; then
        if [[ "$(which brew)" == '' ]]; then
            echo "Developer need 7zip."
            echo "Install Homebrew? (Y/n)"
            read -n 1 INPUT_YN
            if [[ "$INPUT_YN" == "Y" ]]; then
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
        fi
        brew install p7zip
        echo "brew install p7zip > Install p7zip OK"
    fi
fi
#### DBeaver
export DBEAVER_HOME=$DEV_HOME/opt/dbeaver
if [[ ! "$PATH" =~ $DBEAVER_HOME ]]; then
    export PATH=$PATH:$DBEAVER_HOME
fi
#### IntelliJ
export INTELLIJ_HOME=$DEV_HOME/opt/intellij
if [[ ! "$PATH" =~ $INTELLIJ_HOME ]]; then
    export PATH=$PATH:$INTELLIJ_HOME/bin
fi
#### Visual Studio Code
export VSCODE_HOME=$DEV_HOME/opt/vscode
if [[ ! "$PATH" =~ $VSCODE_HOME ]]; then
    export PATH=$PATH:$VSCODE_HOME/bin
fi
#### FileZilla
export FILEZILLA_HOME=$DEV_HOME/opt/filezilla
if [[ ! "$PATH" =~ $FILEZILLA_HOME ]]; then
    export PATH=$PATH:$FILEZILLA_HOME
fi
#### Apache Ant
export ANT_HOME=$DEV_HOME/opt/ant
if [[ ! "$PATH" =~ $ANT_HOME ]]; then
    export PATH=$PATH:$ANT_HOME/bin
fi
#### Apache Maven
export MAVEN_HOME=$DEV_HOME/opt/maven
export M2_HOME=$DEV_HOME/opt/maven
if [[ ! "$PATH" =~ $MAVEN_HOME ]]; then
    export PATH=$PATH:$MAVEN_HOME/bin
fi
#### Sublime
export SUBLIME_HOME=$DEV_HOME/opt/sublime
if [[ ! "$PATH" =~ $SUBLIME_HOME ]]; then
    export PATH=$PATH:$SUBLIME_HOME
fi