#!/bin/bash
#### 7-Zip
export PATH=$PATH:$DEV_HOME/opt/7zip
#### DBeaver
export DBEAVER_HOME=$DEV_HOME/opt/dbeaver
if [[ ! "$PATH" =~ $DBEAVER_HOME ]]; then
    export PATH=$PATH:$DBEAVER_HOME
fi
#### IntelliJ
export INTELLIJ_HOME=$DEV_HOME/opt/intellij/bin
if [[ ! "$PATH" =~ $INTELLIJ_HOME ]]; then
    export PATH=$PATH:$INTELLIJ_HOME
fi
#### Visual Studio Code
export VSCODE_HOME=$DEV_HOME/opt/vscode
if [[ ! "$PATH" =~ $VSCODE_HOME ]]; then
    export PATH=$PATH:$VSCODE_HOME/bin
fi
#### FileZilla
export FILEZILLA_HOME=$DEV_HOME/opt/filezilla
if [[ ! "$PATH" =~ $FILEZILLA_HOME ]]; then
    export PATH=$PATH:$FILEZILLA_HOME
fi
#### Apache Ant
export ANT_HOME=$DEV_HOME/opt/ant
if [[ ! "$PATH" =~ $ANT_HOME ]]; then
    export PATH=$PATH:$ANT_HOME/bin
fi
