#!/bin/bash

. $DEV_HOME/etc/dbeaver.conf
####
####
installonWindows() {
    downloadPath=$(downloadapp --type zip --url $DBEAVER_DOWNLOAD_URL_WINDOWS --name $DBEAVER_FOLDER_NAME)
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    echo "Download path: $downloadPath"
    unarchiver --src $downloadPath --inside-folder dbeaver --folder $DBEAVER_FOLDER_NAME
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    export DBEAVER_HOME=$DEV_HOME/opt/$DBEAVER_FOLDER_NAME
    unarchivePath=$DEV_HOME/tmp/$DBEAVER_FOLDER_NAME
    installapp --dir $DBEAVER_HOME --src $unarchivePath
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    setupapp --name dbeaver --command "start $DBEAVER_HOME/dbeaver.exe"
}
installOnMacOS() {
    installapp -t dmg -s DBeaver.app $DBEAVER_HOME dbeaver $DBEAVER_DOWNLOAD_URL_MACOS
}
installOnLinux() {
    echo "Can't support!!!"
}
####
####
installFail() {
    echo "Install failed!!!"
    exit 1
}

if [[ $OS_WINDOWS == "Y" ]]; then
    installonWindows
elif [[ $OS_MACOS == "Y" ]]; then
    installOnMacOS
elif [[ $OS_LINUX == "Y" ]]; then
    installOnLinux
fi
