#!/bin/bash

. $DEV_HOME/etc/vscode.conf
####
####
installonWindows() {
    folderName=$VSCODE_FOLDER_NAME_WINDOWS
    if [[ "$1" != "" ]] && [[ -f $1 ]]; then
	echo "Install Application from $1"
        offline="--file $1"
    fi
    downloadPath=$(downloadapp --type zip --url $VSCODE_DOWNLOAD_URL_WINDOWS --name $folderName $offline)
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    echo "Download path: $downloadPath"
    unarchiver --src $downloadPath --folder $folderName
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    export VSCODE_HOME=$DEV_HOME/opt/$folderName
    unarchivePath=$DEV_HOME/tmp/$folderName
    installapp --dir $VSCODE_HOME --src $unarchivePath
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    command="params=
if [[ \"\$1\" != \"\" ]] && [[ -d \"\$1\" ]]; then
    cd \$1
    params=\".\"
elif [[ -f \"\$1\" ]]; then
    params=\"\$1\"
fi
$VSCODE_HOME/bin/code \$params
"
    setupapp --name vscode --command "$command"
}
installOnMacOS() {
    folderName=$VSCODE_FOLDER_NAME_MACOS
    downloadPath=$(downloadapp --url $VSCODE_DOWNLOAD_URL_WINDOWS)
}
installOnLinux() {
    echo "Can't support!!!"
}
####
####
installFail() {
    echo "Install failed!!!"
    exit 1
}

if [[ $OS_WINDOWS == "Y" ]]; then
    installonWindows $*
elif [[ $OS_MACOS == "Y" ]]; then
    installOnMacOS
elif [[ $OS_LINUX == "Y" ]]; then
    installOnLinux
fi
