#!/bin/bash

. $DEV_HOME/etc/vscode.conf
####
####
installonWindows() {
    folderName=$VSCODE_FOLDER_NAME_WINDOWS
    if [[ "$1" != "" ]] && [[ -f $1 ]]; then
	echo "Install Application from $1"
        offline="--file $1"
    fi
    downloadPath=$(downloadapp --type zip --url $VSCODE_DOWNLOAD_URL_WINDOWS --name $folderName $offline)
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    echo "Download path: $downloadPath"
    unarchiver --src $downloadPath --folder $folderName
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    export VSCODE_HOME=$DEV_HOME/opt/$folderName
    unarchivePath=$DEV_HOME/tmp/$folderName
    installapp --dir $VSCODE_HOME --src $unarchivePath
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    setupAppOnWindows
}
installOnMacOS() {
    folderName=$VSCODE_FOLDER_NAME_MACOS
    downloadPath=$(downloadapp --type zip --url $VSCODE_DOWNLOAD_URL_MACOS --name $folderName)
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    echo "Download path: $downloadPath"
    applicationName="$VSCODE_APPLICATION_NAME_MACOS"
    unarchiver --src $downloadPath --folder $folderName 
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    export VSCODE_HOME=$DEV_HOME/opt/$folderName
    unarchivePath=$DEV_HOME/tmp/$folderName
    installapp --dir $VSCODE_HOME --src $unarchivePath
    if [[ $? != 0 ]]; then
        installFail
        return 1
    fi
    setupapp --name vscode --command "open -a \"$VSCODE_HOME/$applicationName\" \$*"
}
installOnLinux() {
    echo "Can't support!!!"
}
####
setupAppOnWindows() {
    command="params=
if [[ \"\$1\" != \"\" ]] && [[ -d \"\$1\" ]]; then
    cd \$1
    params=\".\"
elif [[ -f \"\$1\" ]]; then
    params=\"\$1\"
fi
export MSYS_NO_PATHCONV=1
\"$VSCODE_HOME/bin/code\" \$params
unset MSYS_NO_PATHCONV
"
    setupapp --name vscode --command "$command"
}
####
####
checkAppExist() {
    type code > /dev/null && echo "Y" || echo "N"
}
askSetApp() {
    if [[ $OS_WINDOWS == "Y" ]]; then
        VSCODE_HOME="$(cd "$(dirname "$(which code)")/.."; pwd)"
    fi

    echo -e "Installed Application Path: $VSCODE_HOME\n"
    read -p "Do you want to use an installed application? [Y/n] " answer
    if [[ $answer == "Y" ]]; then
        setApp
        exit 0
    fi
    echo
    echo Please uninstall the application first!!!
    exit 1
}
setApp() {
    if [[ $OS_WINDOWS == "Y" ]]; then
        setupAppOnWindows
    fi
    if [[ -f $DEV_HOME/usr/bin/vscode ]]; then
        echo Set up VS Code is finish.
    fi
}
####
####
installFail() {
    echo "Install failed!!!"
    exit 1
}

if [[ $(checkAppExist) == "Y" ]]; then
    echo VS Code is installed.
    askSetApp
    exit 0
fi

if [[ $OS_WINDOWS == "Y" ]]; then
    installonWindows $*
elif [[ $OS_MACOS == "Y" ]]; then
    installOnMacOS
elif [[ $OS_LINUX == "Y" ]]; then
    installOnLinux
fi
